language: node_js
node_js:
  - 4
  - 7
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_install:
  - npm install -g coveralls
script:
  - npm test -- --coverage && cat ./coverage/lcov.info | coveralls